---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: smartos
    driver_config:
      box: livinginthepast/smartos-base64
      box_url: https://atlas.hashicorp.com/livinginthepast/boxes/smartos-base64
      vagrantfile_erb: test/templates/Vagrantfile.smartos.erb
    provisioner:
      name: chef_zero
      sudo: true
      chef_omnibus_url: https://raw.github.com/wanelo-chef/chef-bootstrap/master/latest.sh

suites:
  - name: default
    run_list:
      - recipe[git::default]
    attributes:
